# Generated by Django 5.1.1 on 2026-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection (visible to applicant)"
            ),
        ),
    ]
