# Generated by Django 6.0.2 on 2026-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobview_jobpreference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobview',
            new_name='jobs_jobvie_user_id_1f2d90_idx',
            old_name='jobs_jobvie_user_id_viewed_idx',
        ),
        migrations.RenameIndex(
            model_name='jobview',
            new_name='jobs_jobvie_job_id_f6a7d8_idx',
            old_name='jobs_jobvie_job_id_viewed_idx',
        ),
    ]
