# Generated by Django 5.1.1 on 2026-02-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_bio_profile_company_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("hr_manager", "HR Manager"),
                            ("recruiter", "Recruiter"),
                            ("hiring_manager", "Hiring Manager"),
                            ("interviewer", "Interviewer"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "permissions",
                    models.CharField(
                        choices=[
                            ("full_access", "Full Access - Can manage everything"),
                            (
                                "manage_jobs",
                                "Manage Jobs - Can post, edit, and delete jobs",
                            ),
                            (
                                "view_applications",
                                "View Applications - Can view and review applications",
                            ),
                            (
                                "interview_candidates",
                                "Interview Candidates - Can review and update application status",
                            ),
                            (
                                "view_only",
                                "View Only - Can only view jobs and applications",
                            ),
                        ],
                        default="view_only",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-invited_at"],
                "unique_together": {("company_owner", "email")},
            },
        ),
    ]
