# Generated by Django 6.0.2 on 2026-02-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teammember_invitation_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', help_text='Configuration name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Use this configuration for sending emails')),
                ('backend', models.CharField(choices=[('smtp', 'SMTP (Email Server)'), ('console', 'Console (Development - prints to terminal)')], default='console', help_text='Email backend to use', max_length=20)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server (e.g., smtp.gmail.com, smtp.sendgrid.net)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port (587 for TLS, 465 for SSL, 25 for non-encrypted)')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (recommended)')),
                ('smtp_use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP username (usually your email address)', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP password or app password', max_length=255)),
                ('from_email', models.EmailField(default='noreply@prorecruiter.ai', help_text="Default 'From' email address", max_length=254)),
                ('from_name', models.CharField(default='ProRecruiter AI', help_text="Default 'From' name", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
